# frozen_string_literal: true

require_relative '../../hots_data/entity'

module HotsData
  module Entities
    class PlayerStats < Entity
      attribute :id
      attribute :role
      attribute :team
      attribute :level
      attribute :deaths
      attribute :deaths_count
      attribute :assists
      attribute :healing
      attribute :solo_kill
      attribute :wins_male
      attribute :hero_name
      attribute :player_id
      attribute :replay_id
      attribute :game_score
      attribute :plays_male
      attribute :takedowns
      attribute :team_level
      attribute :town_kills
      attribute :kill_count
      attribute :hero_damage
      attribute :wins_diablo
      attribute :wins_female
      attribute :death_count
      attribute :creep_damage
      attribute :damage_taken
      attribute :plays_diablo
      attribute :plays_female
      attribute :self_healing
      attribute :siege_damage
      attribute :wins_support
      attribute :wins_warrior
      attribute :level_events
      attribute :seconds_dead
      attribute :total_out_dmg
      attribute :minion_damage
      attribute :plays_support
      attribute :plays_warrior
      attribute :summon_damage
      attribute :team_wins_male
      attribute :wins_assassin
      attribute :wins_warcraft
      attribute :plays_assassin
      attribute :plays_war_craft
      attribute :team_takedowns
      attribute :time_on_payload
      attribute :time_spent_dead
      attribute :wins_star_craft
      attribute :meta_experience
      attribute :plays_star_craft
      attribute :team_wins_diablo
      attribute :team_wins_female
      attribute :wins_specialist
      attribute :forts_destroyed
      attribute :plays_specialist
      attribute :structure_damage
      attribute :casted_abilities
      attribute :solo_deaths_count
      attribute :votes_received_by
      attribute :escapes_performed
      attribute :merc_camp_captures
      attribute :on_fire_time_on_fire
      attribute :team_wins_warcraft
      attribute :kill_count_minions
      attribute :kill_count_neutral
      attribute :regen_globes_taken
      attribute :highest_kill_streak
      attribute :outnumbered_deaths
      attribute :team_wins_star_craft
      attribute :gardens_plant_damage
      attribute :time_c_cd_enemy_heroes
      attribute :watch_tower_captures
      attribute :kill_count_buildings
      attribute :teamfight_hero_damage
      attribute :vengeances_performed
      attribute :clutch_heals_performed
      attribute :killed_treasure_goblin
      attribute :mines_skulls_collected
      attribute :teamfight_damage_taken
      attribute :teamfight_healing_done
      attribute :gardens_seeds_collected
      attribute :experience_contribution
      attribute :time_rooting_enemy_heroes
      attribute :protection_given_to_allies
      attribute :time_stunning_enemy_heroes
      attribute :starcraft_pieces_collected
      attribute :time_silencing_enemy_heroes
      attribute :end_of_match_award_mvp_boolean
      attribute :teamfight_escapes_performed
      attribute :lunar_new_year_event_completed
      attribute :starcraft_daily_event_completed
      attribute :end_of_match_award0_deaths_boolean
      attribute :end_of_match_award_hat_trick_boolean
      attribute :end_of_match_award_given_to_nonwinner
      attribute :end_of_match_award_most_kills_boolean
      attribute :end_of_match_award_most_roots_boolean
      attribute :end_of_match_award_most_stuns_boolean
      attribute :end_of_match_award_map_specific_boolean
      attribute :end_of_match_award_most_escapes_boolean
      attribute :end_of_match_award_most_healing_boolean
      attribute :lunar_new_year_rooster_event_completed
      attribute :end_of_match_award_clutch_healer_boolean
      attribute :end_of_match_award_most_altar_damage_done
      attribute :end_of_match_award_most_silences_boolean
      attribute :end_of_match_award_most_coins_paid_boolean
      attribute :end_of_match_award_most_protection_boolean
      attribute :lunar_new_year_succesful_artifact_turn_ins
      attribute :end_of_match_award_most_damage_taken_boolean
      attribute :end_of_match_award_most_time_pushing_boolean
      attribute :end_of_match_award_most_gems_turned_in_boolean
      attribute :end_of_match_award_most_time_in_temple_boolean
      attribute :end_of_match_award_highest_kill_streak_boolean
      attribute :end_of_match_award0_outnumbered_deaths_boolean
      attribute :end_of_match_award_most_damage_to_plants_boolean
      attribute :end_of_match_award_most_hero_damage_done_boolean
      attribute :end_of_match_award_most_immortal_damage_boolean
      attribute :end_of_match_award_most_nuke_damage_done_boolean
      attribute :end_of_match_award_most_xp_contribution_boolean
      attribute :end_of_match_award_most_curse_damage_done_boolean
      attribute :end_of_match_award_most_damage_to_minions_boolean
      attribute :end_of_match_award_most_siege_damage_done_boolean
      attribute :end_of_match_award_most_skulls_collected_boolean
      attribute :end_of_match_award_most_damage_done_to_zerg_boolean
      attribute :end_of_match_award_most_daredevil_escapes_boolean
      attribute :end_of_match_award_most_merc_camps_captured_boolean
      attribute :end_of_match_award_most_vengeances_performed_boolean
      attribute :end_of_match_award_most_teamfight_damage_taken_boolean
      attribute :end_of_match_award_most_teamfight_healing_done_boolean
      attribute :end_of_match_award_most_dragon_shrines_captured_boolean
      attribute :end_of_match_award_most_teamfight_hero_damage_done_boolean
    end
  end
end
